CONF_CTRL_PORT = "control_port"
CONF_NOTIFY_PORT = "notify_port"
CONF_NOTIFICATIONS = "notifications"
CONF_PROTO_VER = "protocol_version"
CONF_DISCOVER = "discover"
CONF_MANUAL = "manual"

DOMAIN = "emotiva"
DEFAULT_NAME = "Emotiva Processor"
SERVICE_SEND_COMMAND = "send_command"